import { ClerkProvider, UserButton, auth } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {userId && <UserButton afterSignOutUrl="/" />}
          {!userId && <Link href="/sign-in">Sign In</Link>}
          <nav>
            <Link href="/">Home</Link>
            <Link href="/posts">Posts</Link>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
