import { ClerkProvider, UserButton, auth, currentUser } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();
  console.log("userId", userId);
  const user = await currentUser();
  console.log("user", user);
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {userId && <UserButton afterSignOutUrl="/" />}
          {!userId && <Link href="/sign-in">Sign In</Link>}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
