import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton, auth } from "@clerk/nextjs";
import { sql } from "@vercel/postgres";
import CreateProfile from "@/components/CreateProfile";
// import { db } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();
  console.log(userId);
  // go and get the user profile from our db
  const profileRes =
    await sql`SELECT * FROM profiles WHERE clerk_user_id = ${userId}`;

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <UserButton afterSignOutUrl="/" />
          <h1>TimTalk</h1>
          {/* if the user has a profile, carry on as normal */}
          {profileRes.rowCount !== 0 && children}

          {/* if the user DOESN'T has a profile, show the CreateProfile component */}
          {profileRes.rowCount === 0 && <CreateProfile />}
        </body>
      </html>
    </ClerkProvider>
  );
}
